.TH "src Directory Reference" 3 "Version v5.0.0" "BOCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcalc_grids\&.c\fP"
.br
.RI "Main driver of the cgff calculation\&. "
.ti -1c
.RI "file \fBcalc_grids\&.h\fP"
.br
.ti -1c
.RI "file \fBcalc_ref_potential\&.c\fP"
.br
.ti -1c
.RI "file \fBcalc_ref_potential\&.h\fP"
.br
.ti -1c
.RI "file \fBcgff\&.c\fP"
.br
.RI "MPI driver for the cgff calculation\&. "
.ti -1c
.RI "file \fBcgff_fn\&.c\fP"
.br
.RI "Helper functions for the cgff calculation\&. "
.ti -1c
.RI "file \fBcgff_fn\&.h\fP"
.br
.RI "Helper functions for the cgff calculation\&. "
.ti -1c
.RI "file \fBcgff_types\&.h\fP"
.br
.RI "Defines properties and structures of the cgff and cgmap calculations\&. "
.ti -1c
.RI "file \fBcgmap\&.c\fP"
.br
.RI "Driver for the cgmap executable\&. "
.ti -1c
.RI "file \fBcgmap_legacy\&.c\fP"
.br
.ti -1c
.RI "file \fBematch\&.c\fP"
.br
.ti -1c
.RI "file \fBematch_func\&.c\fP"
.br
.ti -1c
.RI "file \fBematch_func\&.h\fP"
.br
.ti -1c
.RI "file \fBematch_types\&.h\fP"
.br
.ti -1c
.RI "file \fBfeatures\&.h\fP"
.br
.ti -1c
.RI "file \fBgromacs_topology\&.c\fP"
.br
.ti -1c
.RI "file \fBgromacs_topology\&.h\fP"
.br
.ti -1c
.RI "file \fBio_output\&.c\fP"
.br
.RI "Functions related to writing cgff output\&. "
.ti -1c
.RI "file \fBio_output\&.h\fP"
.br
.ti -1c
.RI "file \fBio_read\&.c\fP"
.br
.RI "Functions related to cgff and cgmap input\&. "
.ti -1c
.RI "file \fBio_read\&.h\fP"
.br
.ti -1c
.RI "file \fBLDD\&.c\fP"
.br
.ti -1c
.RI "file \fBLDD\&.h\fP"
.br
.ti -1c
.RI "file \fBLDD_calc\&.c\fP"
.br
.ti -1c
.RI "file \fBmake_LDPDF\&.c\fP"
.br
.ti -1c
.RI "file \fBread_map\&.c\fP"
.br
.RI "Functions related to reading in a map\&.top file\&. "
.ti -1c
.RI "file \fBread_map\&.h\fP"
.br
.ti -1c
.RI "file \fBread_parameters\&.c\fP"
.br
.RI "Functions related to reading in settings for the cgff calculation\&. "
.ti -1c
.RI "file \fBread_parameters\&.h\fP"
.br
.ti -1c
.RI "file \fBsafe_mem\&.c\fP"
.br
.RI "Functions related to safe memory management\&. "
.ti -1c
.RI "file \fBsafe_mem\&.h\fP"
.br
.RI "Functions related to safe memory management\&. "
.ti -1c
.RI "file \fBsolv_lin_eqns\&.c\fP"
.br
.RI "Functions related to solving sets of linear equations with lapack libraries\&. "
.ti -1c
.RI "file \fBsolv_lin_eqns\&.h\fP"
.br
.ti -1c
.RI "file \fBtable_functions\&.c\fP"
.br
.RI "Functions for generating table files for gromacs 4 use\&. "
.ti -1c
.RI "file \fBtable_functions\&.h\fP"
.br
.ti -1c
.RI "file \fBtable_types\&.h\fP"
.br
.ti -1c
.RI "file \fBtables\&.c\fP"
.br
.RI "Driver for the tables executable\&. "
.ti -1c
.RI "file \fBtransf_map\&.c\fP"
.br
.RI "Functions related to mapping to a cg representation\&. "
.ti -1c
.RI "file \fBtransf_map\&.h\fP"
.br
.ti -1c
.RI "file \fBtranslator\&.c\fP"
.br
.RI "This is a driver for the translator exec\&. Generates \&.btp files\&. "
.ti -1c
.RI "file \fBwnoid_math\&.c\fP"
.br
.RI "Functions for basic math operations not basic enough to be in the standard c math library\&. "
.ti -1c
.RI "file \fBwnoid_math\&.h\fP"
.br
.in -1c
