.TH "features.h" 3 "Version v5.0.0" "BOCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
features.h
.SH SYNOPSIS
.br
.PP
\fR#include <stdc\-predef\&.h>\fP
.br
\fR#include <sys/cdefs\&.h>\fP
.br
\fR#include <gnu/stubs\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__KERNEL_STRICT_NAMES\fP"
.br
.ti -1c
.RI "#define \fB__USE_ANSI\fP   1"
.br
.ti -1c
.RI "#define \fB__GNUC_PREREQ\fP(maj,  min)   0"
.br
.ti -1c
.RI "#define \fB_BSD_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_SVID_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_POSIX_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_POSIX_C_SOURCE\fP   200809L"
.br
.ti -1c
.RI "#define \fB__USE_POSIX_IMPLICITLY\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX2\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX199309\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_POSIX199506\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_XOPEN2K\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_ISOC95\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_ISOC99\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_XOPEN2K8\fP   1"
.br
.ti -1c
.RI "#define \fB_ATFILE_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_MISC\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_BSD\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_SVID\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_ATFILE\fP   1"
.br
.ti -1c
.RI "#define \fB__USE_FORTIFY_LEVEL\fP   0"
.br
.ti -1c
.RI "#define \fB__GNU_LIBRARY__\fP   6"
.br
.ti -1c
.RI "#define \fB__GLIBC__\fP   2"
.br
.ti -1c
.RI "#define \fB__GLIBC_MINOR__\fP   17"
.br
.ti -1c
.RI "#define \fB__GLIBC_PREREQ\fP(maj,  min)   	((\fB__GLIBC__\fP << 16) + \fB__GLIBC_MINOR__\fP >= ((maj) << 16) + (min))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __GLIBC__   2"

.SS "#define __GLIBC_MINOR__   17"

.SS "#define __GLIBC_PREREQ(maj, min)   	((\fB__GLIBC__\fP << 16) + \fB__GLIBC_MINOR__\fP >= ((maj) << 16) + (min))"

.SS "#define __GNU_LIBRARY__   6"

.SS "#define __GNUC_PREREQ(maj, min)   0"

.SS "#define __KERNEL_STRICT_NAMES"

.SS "#define __USE_ANSI   1"

.SS "#define __USE_ATFILE   1"

.SS "#define __USE_BSD   1"

.SS "#define __USE_FORTIFY_LEVEL   0"

.SS "#define __USE_ISOC95   1"

.SS "#define __USE_ISOC99   1"

.SS "#define __USE_MISC   1"

.SS "#define __USE_POSIX   1"

.SS "#define __USE_POSIX199309   1"

.SS "#define __USE_POSIX199506   1"

.SS "#define __USE_POSIX2   1"

.SS "#define __USE_POSIX_IMPLICITLY   1"

.SS "#define __USE_SVID   1"

.SS "#define __USE_XOPEN2K   1"

.SS "#define __USE_XOPEN2K8   1"

.SS "#define _ATFILE_SOURCE   1"

.SS "#define _BSD_SOURCE   1"

.SS "#define _POSIX_C_SOURCE   200809L"

.SS "#define _POSIX_SOURCE   1"

.SS "#define _SVID_SOURCE   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for BOCS from the source code\&.
