.TH "tables.c" 3 "Version v5.0.0" "BOCS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tables.c \- Driver for the tables executable\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdio\&.h>\fP
.br
\fR#include <string\&.h>\fP
.br
\fR#include <stdlib\&.h>\fP
.br
\fR#include <math\&.h>\fP
.br
\fR#include 'table_types\&.h'\fP
.br
\fR#include 'safe_mem\&.h'\fP
.br
\fR#include 'read_parameters\&.h'\fP
.br
\fR#include 'table_functions\&.h'\fP
.br
\fR#include 'io_read\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Driver for the tables executable\&. 


.PP
\fBAuthors\fP
.RS 4
Will Noid, Wayne Mullinax, Joseph Rudzinski, Nicholas Dunn 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for BOCS from the source code\&.
